### ISSUE TITLE
Issuer fails if second context is an object

### ISSUE THREAD

**Issue by aljones15** [filip26/iron-verifiable-credentials#50]
When the following is sent to the issuer:

```js
{
  "credential": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      {
        "@context": {
          "@protected": true,
          "id": "@id",
          "type": "@type",
          "license": {
            "@id": "https://w3id.org/vdl#license",
            "@type": "@id"
          },
          "Iso18013DriversLicenseCredential": "https://w3id.org/vdl#Iso18013DriversLicenseCredential",
          "Iso18013DriversLicense": {
            "@id": "https://w3id.org/vdl#Iso18013DriversLicense",
            "@context": {
              "@protected": true,
              "id": "@id",
              "type": "@type",
              "family_name": {
                "@id": "https://w3id.org/vdl#family_name"
              },
              "given_name": {
                "@id": "https://w3id.org/vdl#given_name"
              },
              "birth_date": {
                "@id": "https://w3id.org/vdl#birth_date"
              },
              "issue_date": {
                "@id": "https://w3id.org/vdl#issue_date",
                "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
              },
              "expiry_date": {
                "@id": "https://w3id.org/vdl#expiry_date",
                "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
              },
              "issuing_country": {
                "@id": "https://w3id.org/vdl#issuing_country"
              },
              "issuing_authority": {
                "@id": "https://w3id.org/vdl#issuing_authority"
              },
              "document_number": {
                "@id": "https://w3id.org/vdl#document_number"
              },
              "administrative_number": {
                "@id": "https://w3id.org/vdl#administrative_number"
              },
              "driving_privileges": {
                "@id": "https://w3id.org/vdl#driving_privileges",
                "@type": "@json"
              },
              "un_distinguishing_sign": {
                "@id": "https://w3id.org/vdl#un_distinguishing_sign"
              },
              "gender": {
                "@id": "https://w3id.org/vdl#gender"
              },
              "height": {
                "@id": "https://w3id.org/vdl#height"
              },
              "weight": {
                "@id": "https://w3id.org/vdl#weight"
              },
              "eye_color": {
                "@id": "https://w3id.org/vdl#eye_color"
              },
              "hair_color": {
                "@id": "https://w3id.org/vdl#hair_color"
              },
              "birth_place": {
                "@id": "https://w3id.org/vdl#birth_place"
              },
              "resident_address": {
                "@id": "https://w3id.org/vdl#resident_address"
              },
              "portrait": {
                "@id": "https://w3id.org/vdl#portrait"
              },
              "portrait_capture_date": {
                "@id": "https://w3id.org/vdl#portrait_capture_date"
              },
              "age_in_years": {
                "@id": "https://w3id.org/vdl#age_in_years"
              },
              "age_birth_year": {
                "@id": "https://w3id.org/vdl#age_birth_year"
              },
              "issuing_jurisdiction": {
                "@id": "https://w3id.org/vdl#issuing_jurisdiction"
              },
              "nationality": {
                "@id": "https://w3id.org/vdl#nationality"
              },
              "resident_city": {
                "@id": "https://w3id.org/vdl#resident_city"
              },
              "resident_state": {
                "@id": "https://w3id.org/vdl#resident_state"
              },
              "resident_postal_code": {
                "@id": "https://w3id.org/vdl#resident_postal_code"
              },
              "name_national_character": {
                "@id": "https://w3id.org/vdl#name_national_character"
              },
              "signature_usual_mark": {
                "@id": "https://w3id.org/vdl#signature_usual_mark"
              }
            }
          }
        }
      }
    ],
    "type": [
      "VerifiableCredential",
      "Iso18013DriversLicenseCredential"
    ],
    "credentialSubject": {
      "id": "did:key:z6MkoiCsEDseNGMcHwbLnexFFMp1FZWf2cyfy8b5spwDKe3b",
      "license": {
        "type": "Iso18013DriversLicense",
        "document_number": "542426814",
        "family_name": "TURNER",
        "given_name": "SUSAN",
        "portrait": "/9j/4AAQSkZJRgABAQEAkACQA...gcdgck5HtRRSClooooP/2Q==",
        "birth_date": "1998-08-28",
        "issue_date": "2018-01-15T10:00:00Z",
        "expiry_date": "2022-08-27T12:00:00Z",
        "issuing_country": "US",
        "issuing_authority": "AL",
        "driving_privileges": [
          {
            "codes": [
              {
                "code": "D"
              }
            ],
            "vehicle_category_code": "D",
            "issue_date": "2019-01-01",
            "expiry_date": "2027-01-01"
          },
          {
            "codes": [
              {
                "code": "C"
              }
            ],
            "vehicle_category_code": "C",
            "issue_date": "2019-01-01",
            "expiry_date": "2017-01-01"
          }
        ],
        "un_distinguishing_sign": "USA"
      }
    },
    "issuer": "did:key:z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y",
    "id": "urn:uuid:8a5073ee-0968-45b3-b0f8-16bbac6d248c",
    "expirationDate": "2025-11-10T18:41:46Z"
  },
  "options": {
    "type": "Ed25519Signature2020"
  }
}
        ❌ should be issued by API Catalog
        AssertionError: expected { id: 'INTERNAL', message: 'Internal' } to have property '@context'
    at testCredential (file:///home/liminal18/Programs/nodejs/w3c/ccg/vdl-test-suite/tests/assertions.js:19:26)
    at Context.<anonymous> (file:///home/liminal18/Programs/nodejs/w3c/ccg/vdl-test-suite/tests/10-interop.js:154:13)
    at processImmediate (node:internal/timers:466:21) {
  showDiff: false,
  actual: { id: 'INTERNAL', message: 'Internal' },
  expected: undefined
}
```

The issuer fails with an internal error.

**Comment by filip26** [comment]
Thank you for reporting it. Actually, the context in the example is invalid according to JSON-LD 1.1. specification as it redefines protected terms. (see `protected` keywords in the example) 

I'll update the library to provide more meaningful error message than internal error.

**Comment by filip26** [comment]
digging more into it, it seems the issue is the second context declaration having using `@context` keyword.

```
 {
        "@context": {
```
if you omit the` @context` keyword and wrapping JSON object then it works. Have to check if this is valid JSON-LD 1.1. syntax.

**Comment by filip26** [comment]
after checking the spec and processing algorithm there is no support for having embedded local context using `@context` keyword. Please, unwrap the second context to make it work.

**Comment by filip26** [comment]
please note the difference between a remote (must have `@context` declaration) and local context (must not have `@context` declaration)
